config/routes.rb
Rails.application.routes.draw do
  resources :games
  resources :lineups
  resources :teams
  resources :owners
  resources :leagues
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/league.rb
class League < ApplicationRecord
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  before_action :set_league, only: [:show, :edit, :update, :destroy]

  # GET /leagues
  # GET /leagues.json
  def index
    @leagues = League.all
  end

  # GET /leagues/1
  # GET /leagues/1.json
  def show
  end

  # GET /leagues/new
  def new
    @league = League.new
  end

  # GET /leagues/1/edit
  def edit
  end

  # POST /leagues
  # POST /leagues.json
  def create
    @league = League.new(league_params)

    respond_to do |format|
      if @league.save
        format.html { redirect_to @league, notice: 'League was successfully created.' }
        format.json { render :show, status: :created, location: @league }
      else
        format.html { render :new }
        format.json { render json: @league.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leagues/1
  # PATCH/PUT /leagues/1.json
  def update
    respond_to do |format|
      if @league.update(league_params)
        format.html { redirect_to @league, notice: 'League was successfully updated.' }
        format.json { render :show, status: :ok, location: @league }
      else
        format.html { render :edit }
        format.json { render json: @league.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leagues/1
  # DELETE /leagues/1.json
  def destroy
    @league.destroy
    respond_to do |format|
      format.html { redirect_to leagues_url, notice: 'League was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_league
      @league = League.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def league_params
      params.require(:league).permit(:name, :url, :founded)
    end
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/views/leagues/_form.html.erb
<%= form_with(model: league, local: true) do |form| %>
  <% if league.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(league.errors.count, "error") %> prohibited this league from being saved:</h2>

      <ul>
      <% league.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :league_name %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url, id: :league_url %>
  </div>

  <div class="field">
    <%= form.label :founded %>
    <%= form.text_field :founded, id: :league_founded %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/leagues/edit.html.erb
<h1>Editing League</h1>

<%= render 'form', league: @league %>

<%= link_to 'Show', @league %> |
<%= link_to 'Back', leagues_path %>

app/views/leagues/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Leagues</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Url</th>
      <th>Founded</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @leagues.each do |league| %>
      <tr>
        <td><%= league.name %></td>
        <td><%= league.url %></td>
        <td><%= league.founded %></td>
        <td><%= link_to 'Show', league %></td>
        <td><%= link_to 'Edit', edit_league_path(league) %></td>
        <td><%= link_to 'Destroy', league, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New League', new_league_path %>

app/views/leagues/new.html.erb
<h1>New League</h1>

<%= render 'form', league: @league %>

<%= link_to 'Back', leagues_path %>

app/views/leagues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @league.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @league.url %>
</p>

<p>
  <strong>Founded:</strong>
  <%= @league.founded %>
</p>

<%= link_to 'Edit', edit_league_path(@league) %> |
<%= link_to 'Back', leagues_path %>