config/routes.rb
Rails.application.routes.draw do
  resources :games
  resources :lineups
  resources :teams
  resources :owners
  resources :leagues
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/lineup.rb
class Lineup < ApplicationRecord
  belongs_to :team
  belongs_to :owner
end

app/controllers/lineups_controller.rb
class LineupsController < ApplicationController
  before_action :set_lineup, only: [:show, :edit, :update, :destroy]

  # GET /lineups
  # GET /lineups.json
  def index
    @lineups = Lineup.all
  end

  # GET /lineups/1
  # GET /lineups/1.json
  def show
  end

  # GET /lineups/new
  def new
    @lineup = Lineup.new
  end

  # GET /lineups/1/edit
  def edit
  end

  # POST /lineups
  # POST /lineups.json
  def create
    @lineup = Lineup.new(lineup_params)

    respond_to do |format|
      if @lineup.save
        format.html { redirect_to @lineup, notice: 'Lineup was successfully created.' }
        format.json { render :show, status: :created, location: @lineup }
      else
        format.html { render :new }
        format.json { render json: @lineup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lineups/1
  # PATCH/PUT /lineups/1.json
  def update
    respond_to do |format|
      if @lineup.update(lineup_params)
        format.html { redirect_to @lineup, notice: 'Lineup was successfully updated.' }
        format.json { render :show, status: :ok, location: @lineup }
      else
        format.html { render :edit }
        format.json { render json: @lineup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lineups/1
  # DELETE /lineups/1.json
  def destroy
    @lineup.destroy
    respond_to do |format|
      format.html { redirect_to lineups_url, notice: 'Lineup was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lineup
      @lineup = Lineup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lineup_params
      params.require(:lineup).permit(:score, :result, :team_name, :team_id, :owner_id)
    end
end

app/helpers/lineups_helper.rb
module LineupsHelper
end

app/views/lineups/_form.html.erb
<%= form_with(model: lineup, local: true) do |form| %>
  <% if lineup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lineup.errors.count, "error") %> prohibited this lineup from being saved:</h2>

      <ul>
      <% lineup.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :score %>
    <%= form.text_field :score, id: :lineup_score %>
  </div>

  <div class="field">
    <%= form.label :result %>
    <%= form.number_field :result, id: :lineup_result %>
  </div>

  <div class="field">
    <%= form.label :team_name %>
    <%= form.text_field :team_name, id: :lineup_team_name %>
  </div>

  <div class="field">
    <%= form.label :team_id %>
    <%= form.text_field :team_id, id: :lineup_team_id %>
  </div>

  <div class="field">
    <%= form.label :owner_id %>
    <%= form.text_field :owner_id, id: :lineup_owner_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lineups/edit.html.erb
<h1>Editing Lineup</h1>

<%= render 'form', lineup: @lineup %>

<%= link_to 'Show', @lineup %> |
<%= link_to 'Back', lineups_path %>

app/views/lineups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lineups</h1>

<table>
  <thead>
    <tr>
      <th>Score</th>
      <th>Result</th>
      <th>Team name</th>
      <th>Team</th>
      <th>Owner</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lineups.each do |lineup| %>
      <tr>
        <td><%= lineup.score %></td>
        <td><%= lineup.result %></td>
        <td><%= lineup.team_name %></td>
        <td><%= lineup.team %></td>
        <td><%= lineup.owner %></td>
        <td><%= link_to 'Show', lineup %></td>
        <td><%= link_to 'Edit', edit_lineup_path(lineup) %></td>
        <td><%= link_to 'Destroy', lineup, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lineup', new_lineup_path %>

app/views/lineups/new.html.erb
<h1>New Lineup</h1>

<%= render 'form', lineup: @lineup %>

<%= link_to 'Back', lineups_path %>

app/views/lineups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Score:</strong>
  <%= @lineup.score %>
</p>

<p>
  <strong>Result:</strong>
  <%= @lineup.result %>
</p>

<p>
  <strong>Team name:</strong>
  <%= @lineup.team_name %>
</p>

<p>
  <strong>Team:</strong>
  <%= @lineup.team %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @lineup.owner %>
</p>

<%= link_to 'Edit', edit_lineup_path(@lineup) %> |
<%= link_to 'Back', lineups_path %>